#!/bin/bash
set -euo pipefail

# Dead Code Analysis Script
# Runs multiple static analysis tools to detect unused code
#
# Usage:
#   ./scripts/dead_code_analysis.sh [--fix]
#
# Tools used:
#   - vulture: Dead code detection (classes, methods, variables)
#   - ruff: Unused imports and variables (F401, F841)
#
# Output:
#   - Console summary
#   - Detailed report in docs/dead-code-report.md

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }

REPORT_FILE="$PROJECT_ROOT/docs/dead-code-report.md"
FIX_MODE="${1:-}"

cd "$PROJECT_ROOT"

log_info "Running Dead Code Analysis..."
log_info "Project: $PROJECT_ROOT"
echo ""

# Initialize report
cat > "$REPORT_FILE" << 'EOF'
# Dead Code Analysis Report

**Generated:** $(date)
**Tools:** vulture, ruff

## Summary

EOF

# Run vulture for dead code detection
log_info "Running vulture (dead code detector)..."
VULTURE_OUTPUT=$(.venv/bin/vulture src/ --min-confidence 80 2>&1 | grep -v "WARNING:" || true)
VULTURE_COUNT=$(echo "$VULTURE_OUTPUT" | grep -c "unused" || echo "0")

cat >> "$REPORT_FILE" << EOF

## Vulture Analysis (High Confidence Dead Code)

**Found:** $VULTURE_COUNT items

\`\`\`
$VULTURE_OUTPUT
\`\`\`

EOF

if [[ $VULTURE_COUNT -gt 0 ]]; then
    log_warning "Vulture found $VULTURE_COUNT high-confidence dead code items"
else
    log_success "Vulture found no high-confidence dead code"
fi

# Run vulture at lower confidence for "potentially unused"
log_info "Running vulture (lower confidence)..."
VULTURE_LOW=$(.venv/bin/vulture src/ --min-confidence 60 2>&1 | grep -v "WARNING:" || true)
VULTURE_LOW_COUNT=$(echo "$VULTURE_LOW" | grep -c "unused" || echo "0")

cat >> "$REPORT_FILE" << EOF

## Vulture Analysis (Medium Confidence - Review Carefully)

**Found:** $VULTURE_LOW_COUNT items

These may be false positives (e.g., used via reflection, tests, or external callers):

\`\`\`
$VULTURE_LOW
\`\`\`

EOF

# Run ruff for unused imports/variables
log_info "Running ruff (unused imports and variables)..."
RUFF_OUTPUT=$(.venv/bin/ruff check --select F401,F841 src/ tests/ 2>&1 | grep -v "warning:" || true)
RUFF_COUNT=$(echo "$RUFF_OUTPUT" | grep -cE "^(src|tests)/" 2>/dev/null || echo "0")
RUFF_COUNT=$(echo "$RUFF_COUNT" | head -1)

cat >> "$REPORT_FILE" << EOF

## Ruff Analysis (Unused Imports & Variables)

**Found:** $RUFF_COUNT items

\`\`\`
$RUFF_OUTPUT
\`\`\`

EOF

if [[ $RUFF_COUNT -gt 0 ]]; then
    log_warning "Ruff found $RUFF_COUNT unused imports/variables"

    if [[ "$FIX_MODE" == "--fix" ]]; then
        log_info "Applying automatic fixes..."
        .venv/bin/ruff check --select F401,F841 --fix src/ tests/ 2>&1 || true
        log_success "Fixes applied"
    else
        log_info "Run with --fix to auto-remove unused imports"
    fi
else
    log_success "Ruff found no unused imports/variables"
fi

# Analyze by category
log_info "Analyzing code by category..."

cat >> "$REPORT_FILE" << 'EOF'

## Analysis by Module

### Potentially Unused Infrastructure Code

The following modules contain code that appears unused but may be:
1. **Future infrastructure** - Implemented but not yet wired up
2. **API surface** - Public methods intended for external use
3. **Test fixtures** - Used by test discovery

EOF

# Check each major module
for module in coordination agents core orchestrator; do
    if [[ -d "src/$module" ]]; then
        MODULE_UNUSED=$(.venv/bin/vulture "src/$module/" --min-confidence 60 2>&1 | grep -v "WARNING:" | grep -c "unused" || echo "0")
        echo "| src/$module | $MODULE_UNUSED items |" >> "$REPORT_FILE"
    fi
done

cat >> "$REPORT_FILE" << 'EOF'

## Recommendations

### Safe to Remove (High Confidence)
- Unused local variables marked 100% confidence
- Unused imports in test files

### Review Before Removing (Medium Confidence)
- Enum values that may be used for type checking
- Methods that may be called via dynamic dispatch
- Classes that may be instantiated externally

### Action Items
1. Review each item in the high-confidence list
2. Check if code is genuinely unused or false positive
3. Remove confirmed dead code or add to whitelist
4. Consider adding `# noqa: vulture` comments for intentional API surface

EOF

# Final summary
cat >> "$REPORT_FILE" << EOF

---
*Report generated by dead_code_analysis.sh*
EOF

echo ""
log_success "Dead code analysis complete!"
log_info "Report saved to: $REPORT_FILE"
echo ""
echo "Summary:"
echo "  - Vulture (high confidence): $VULTURE_COUNT items"
echo "  - Vulture (medium confidence): $VULTURE_LOW_COUNT items"
echo "  - Ruff (unused imports/vars): $RUFF_COUNT items"
